# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Maven Build

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt-hotspot
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: bedrockcloud
          path: target/BedrockCloud.jar  
      - name: Upload release
        if: github.ref == 'refs/heads/master'
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          automatic_releases_tag: "latest"
          title: "BedrockCloud release"
          tag: "latest"
          files: |
            target/BedrockCloud.jar
